const ROLES = {
	ADD_EMPLOYEE: "ADD_EMPLOYEE",
	REST_EMPLOYEE_PASSWORD: "REST_EMPLOYEE_PASSWORD",
	CREATE_CATEGORY: "CREATE_CATEGORY",
	PACKAGE_ROLE: "PACKAGE_ROLE",
	BANNER_ROLE: "BANNER_ROLE",
	CART_ROLE: "CART_ROLE",
	ORDER_ROLE: "ORDER_ROLE",
	ADD_MORE_PACKAGE: "ADD_MORE_PACKAGE",
	CUSTOMER_ROLE: "CUSTOMER_ROLE",
	EMPLOYEE_EDIT_ROLE: "EMPLOYEE_EDIT_ROLE",
	TRANSACTIONS: "TRANSACTIONS",
};

module.exports = {
	ROLES,
};
